services:
      app.book.manager:
        class: AppBundle\Manager\BookManager
        arguments: [ '@doctrine.orm.entity_manager', '@form.factory', '@router' ]

      app.category.manager:
        class: AppBundle\Manager\CategoryManager
        arguments: [ '@doctrine.orm.entity_manager', '@form.factory', '@router' ]

      app.theme.manager:
        class: AppBundle\Manager\ThemeManager
        arguments: [ '@doctrine.orm.entity_manager', '@form.factory', '@router' ]